target:
	clang++ -o Timber code/Timber.cpp \
	-I/usr/local/Cellar/sfml/2.5.1_1/include/SFML/ \
	-L/usr/local/Cellar/sfml/2.5.1_1/lib/ \
	-lsfml-network \
	-lsfml-audio \
	-lsfml-graphics \
	-lsfml-window \
	-lsfml-system
